clientTrajectoryFilePath: /home/surveillance/pulsar-location-samosa/data/output/
clientTrajectoryFiles:
- /home/surveillance/pulsar-location-samosa/data/output/0.0_0.txt
indexConfig:
  blockSize: 0.01
  indexType: GEOHASH
  maxX: 34.7757
  maxY: 85.3963
  minX: 33.7757
  minY: 84.3963
locationChangeInterval: 10000
numClients: 10
numPartitionsPerTopic: 1
outputFile: output_10sec_10client.json
payloadFile: payload-1Kb.data
pulsarConfigFile: /home/surveillance/pulsar-location-samosa/pulsar.yaml
testDurationSeconds: 30
